version: '3.0'

services:

  web:
    image: node:17
    volumes:
      - "./src:/app"
    ports:
      - "3333:3333"
    working_dir: /app
    command: node ace serve --watch
    user: 1000:1000
    networks:
      - app-network
    depends_on:
      - db
  
  db:
    image: mysql
    volumes:
      - "./data:/var/lib/mysql"
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root12345 
      - MYSQL_DATABASE=app 
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=user12345
    networks:
      - app-network

networks:
  app-network:
    driver: bridge