version: '3.0'

services:

  web:
    image: php
    volumes:
      - "./src:/app"
    ports:
      - "8000:8000"
    working_dir: /app
    command: php artisan serve --host=0.0.0.0
    user: root
    networks:
      - app-network
    depends_on:
      - db
  
  db:
    image: mysql
    volumes:
      - "./data:/var/lib/mysql"
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root12345 
      - MYSQL_DATABASE=app 
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=user12345
    networks:
      - app-network

networks:
  app-network:
    driver: bridge